---
- name: kubeadm 초기화
  shell: |
    kubeadm init
  register: init_result
  args:
    creates: /etc/kubernetes/admin.conf  

- name: kubectl 설정 폴더
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: 관리자 설정 파일 복사
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes

- name: 조인 명령 실행
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: 조인 명령어를 메모리에 저장
  set_fact:
    k8s_join_command: "{{ join_command_raw.stdout }}"


- name: alias 등록
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED KUBECTL ALIAS"
    block: |
      # kubectl 단축어 설정
      alias k='kubectl'

      # kubectl 자동 완성(Tab) 설정
      source <(kubectl completion bash)

      # 단축어 'k'에서도 자동 완성이 되도록 설정
      complete -o default -F __start_kubectl k
