---
- name: kubeadm 초기화
  shell: |
    kubeadm init
  register: init_result
  args:
    creates: /etc/kubernetes/admin.conf  

- name: kubectl 설정 폴더
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: 관리자 설정 파일 복사
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes

- name: 조인 명령 실행
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: 조인 명령어를 메모리에 저장
  set_fact:
    k8s_join_command: "{{ join_command_raw.stdout }}"


- name: alias 등록
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED KUBECTL ALIAS"
    block: |
      # kubectl 단축어 설정
      alias k='kubectl'

      # kubectl 자동 완성(Tab) 설정
      source <(kubectl completion bash)

      # 단축어 'k'에서도 자동 완성이 되도록 설정
      complete -o default -F __start_kubectl k

- name: "NFS 서버 패키지 설치"
  dnf:
    name: nfs-utils
    state: present

- name: "NFS 서비스 시작 및 활성화"
  service:
    name: nfs-server
    state: started
    enabled: yes

# 2. 공유 디렉토리 생성 및 권한 설정
- name: "NFS 공유 디렉토리 생성 (MariaDB용 포함)"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0777'  # 모든 사용자 읽기/쓰기 권한 부여
    owner: root
    group: root
  loop:
    - /root/nfs-share
    - /root/nfs-share/mysql

# 3. /etc/exports 설정 (NFS 권한 관리)
- name: "NFS exports 설정 파일 작성"
  lineinfile:
    path: /etc/exports
    line: "/root/nfs-share *(rw,sync,no_root_squash)"
    create: yes
  register: exports_result

# 4. 설정 변경 시 즉시 반영
- name: "NFS 내보내기 설정 갱신 (exportfs)"
  shell: "exportfs -ra"
  when: exports_result.changed

